// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Welcome
    {
        [JsonProperty("統計項目別")]
        public string 統計項目別 { get; set; }

        [JsonProperty("細項")]
        public string 細項 { get; set; }

        [JsonProperty("樣本數（人）")]
        public string 樣本數人 { get; set; }

        [JsonProperty("沒有遭受不平等待遇（%）")]
        public string 沒有遭受不平等待遇 { get; set; }

        [JsonProperty("有遭受不平等待遇（%）")]
        public string 有遭受不平等待遇 { get; set; }

        [JsonProperty("有提出申訴（%）")]
        public string 有提出申訴 { get; set; }

        [JsonProperty("沒有提出申訴（%）")]
        public string 沒有提出申訴 { get; set; }
    }

    public partial class Welcome
    {
        public static Welcome[] FromJson(string json) => JsonConvert.DeserializeObject<Welcome[]>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
